permalink: /:title/
markdown: kramdown
highlighter: pygments

paginate: 10
comments: true
paginate_path: "/page/:num"

baseurl: ""
domain_name: devreads.sandordargo.com
google_analytics: UA-89625019-2

source: source
destination: _site
plugins:
  - jekyll-seo-tag
  - jekyll-paginate

# cover: /assets/images/header-cover.png

# site title, description, meta_description, meta_keywords
# Details for the RSS feed generator
name: DevReads
title: The Best Developer Reads
description: "The best books for software developers not only about software development"
meta_description: "The best books for software developers not only about software development"
meta_keywords: "site, website, book, books, development, software, improvement, learn, learning"
url: https://devreads.sandordargo.com
production_url: https://devreads.sandordargo.com
repo: https://github.com/devreads51/devreads51.github.io
disqus_shortname: "sandordargo-github-io"
rss_path: source/
author:
  name: Sandor Dargo
  image: /assets/images/author.jpg
  email: sandor.dargo@gmail.com
  url: https://www.sandordargo.com
  twitter: https://twitter.com/TheDevReads
  github: https://github.com/sandordargo/
  linkedin: https://www.linkedin.com/in/sandor-dargo/
  bio: "C++ Developer, writer, speaker, traveller, happy father of two"

# thought
thought:
  text: Reading must become as natural as eating and breathing to you. It’s not something you do because you feel like it, but because it’s a reflex, a default.
  author: Ryan Holiday

# Plugin: jekyll-assets
assets:
  dirname: /assets
  baseurl: /assets/
  sources:
    - assets/images
    - assets/fonts
    - assets/css
    - assets/js
  cache: true
  gzip: [ text/css, application/javascript ]

# Compress HTML
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  ignore:
    envs: all

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
